- shell:
  - [bash ui/zsh/install.sh, Installing oh-my-zsh]

- link:
    ~/.aliases: ui/zsh/aliases
    ~/.linuxrc: ui/zsh/linuxrc
    ~/.dockerrc: ui/zsh/dockerrc
    ~/.functionsrc: ui/zsh/functionsrc
    ~/.gitrc: ui/zsh/gitrc
    ~/.pythonrc: ui/zsh/pythonrc
    ~/.zshrc: ui/zsh/zshrc
    ~/.macrc: ui/zsh/macrc
    ~/.gitignore_global: ui/zsh/gitignore_global
    ~/.p10k.zsh: ui/zsh/p10k.zsh
