- shell:
  - [bash ui/zsh/install.sh, Installing oh-my-zsh]

- link:
    ~/.aliases: ui/zsh/aliases
    ~/.archlinuxrc: ui/zsh/archlinuxrc
    ~/.dockerrc: ui/zsh/dockerrc
    ~/.functionsrc: ui/zsh/functionsrc
    ~/.gitrc: ui/zsh/gitrc
    ~/.pythonrc: ui/zsh/pythonrc
    ~/.zshrc: ui/zsh/zshrc
